// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbmabkqhyzincaxigztg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtibWFia3FoeXppbmNheGlnenRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NDgwNzQsImV4cCI6MjA3NjAyNDA3NH0.GwVY4Nkh5rakaYrW8bJ6yub5Ys6_hagta1SeP-I2RvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
